syntax = "proto3";

package packets;

option go_package = "pkg/packets";


// game.proto

// 地图数据（服务端推送）
message MapData {
    uint32 width = 1; // 地图宽度（像素）
    uint32 height = 2; // 地图高度（像素）
    uint32 tile_width = 3; // 单个瓦片宽度
    uint32 tile_height = 4; // 单个瓦片高度
    repeated uint32 collision_grid = 5; // 一维碰撞数组（0=可通行，1=阻挡）
    uint32 grid_width = 6; // 网格列数
    uint32 grid_height = 7; // 网格行数
    repeated SpawnPoint spawn_points = 8;
}

message SpawnPoint {
    float x = 1;
    float y = 2;
}
