syntax = "proto3";

package packets;

option go_package = "pkg/packets";

import "common.proto";
import "auth.proto";
import "hall.proto";

message Packet {
    uint64 sender_id = 1;

    oneof msg {
        // common
        IdMessage id = 2;
        ChatMessage chat = 3;
        DenyResponse deny_response = 7;
        OkResponse ok_response = 6;
        DisconnectMessage disconnect = 19;

        // auth
        LoginRequest login_request = 4;
        LoginResponse login_response = 5;
        RegisterRequest register_request = 20;

        // hall
        RoomInfo room_info = 9;
        CreateRoomRequest create_room_request = 12;
        CreateRoomResponse create_room_response = 13;
        JoinRoomRequest join_room_request = 14;
        JoinRoomResponse join_room_response = 15;
        LeaveRoomRequest leave_room_request = 21;
        StartGameRequest start_game_request = 22;
        RoomJoined room_joined = 17;
        User user = 18;
    }
}