syntax = "proto3";

package packets;

option go_package = "pkg/packets";

import "common.proto";
import "auth.proto";
import "game.proto";

message Packet {
    uint64 sender_id = 1;

    oneof msg {
        // ===== Common =====
        IdMessage id = 2;
        ChatMessage chat = 3;
        DenyResponse deny_response = 7;
        OkResponse ok_response = 6;
        DisconnectMessage disconnect = 19;

        // ===== Auth =====
        LoginRequest login_request = 4;
        LoginResponse login_response = 5;
        RegisterRequest register_request = 20;

        // ===== Game =====
        MapData map_data = 50;
    }
}
