syntax = "proto3";

package packets;

option go_package = "pkg/packets";

import "common.proto";
import "auth.proto";
import "game.proto";

message Packet {
    uint64 sender_id = 1;

    oneof msg {
        // ===== Common =====
        IdMessage id = 2;
        ChatMessage chat = 3;
        DenyResponse deny_response = 7;
        OkResponse ok_response = 6;
        DisconnectMessage disconnect = 19;

        // ===== Auth =====
        LoginRequest login_request = 4;
        LoginResponse login_response = 5;
        RegisterRequest register_request = 20;

        // ===== Game =====
        StartGameRequest start_game_request = 22;
        StartGameResponse start_game_response = 33;
        GameStarting game_starting = 34;
        PlayerList player_list = 40;
        PlayerJoined player_joined = 41;
        PlayerLeft player_left = 42;
    }
}