// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: game.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 地图数据（服务端推送）
type MapData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Width         uint32                 `protobuf:"varint,1,opt,name=width,proto3" json:"width,omitempty"`                                             // 地图宽度（像素）
	Height        uint32                 `protobuf:"varint,2,opt,name=height,proto3" json:"height,omitempty"`                                           // 地图高度（像素）
	TileWidth     uint32                 `protobuf:"varint,3,opt,name=tile_width,json=tileWidth,proto3" json:"tile_width,omitempty"`                    // 单个瓦片宽度
	TileHeight    uint32                 `protobuf:"varint,4,opt,name=tile_height,json=tileHeight,proto3" json:"tile_height,omitempty"`                 // 单个瓦片高度
	CollisionGrid []uint32               `protobuf:"varint,5,rep,packed,name=collision_grid,json=collisionGrid,proto3" json:"collision_grid,omitempty"` // 一维碰撞数组（0=可通行，1=阻挡）
	GridWidth     uint32                 `protobuf:"varint,6,opt,name=grid_width,json=gridWidth,proto3" json:"grid_width,omitempty"`                    // 网格列数
	GridHeight    uint32                 `protobuf:"varint,7,opt,name=grid_height,json=gridHeight,proto3" json:"grid_height,omitempty"`                 // 网格行数
	SpawnPoints   []*SpawnPoint          `protobuf:"bytes,8,rep,name=spawn_points,json=spawnPoints,proto3" json:"spawn_points,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapData) Reset() {
	*x = MapData{}
	mi := &file_game_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapData) ProtoMessage() {}

func (x *MapData) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapData.ProtoReflect.Descriptor instead.
func (*MapData) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{0}
}

func (x *MapData) GetWidth() uint32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MapData) GetHeight() uint32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MapData) GetTileWidth() uint32 {
	if x != nil {
		return x.TileWidth
	}
	return 0
}

func (x *MapData) GetTileHeight() uint32 {
	if x != nil {
		return x.TileHeight
	}
	return 0
}

func (x *MapData) GetCollisionGrid() []uint32 {
	if x != nil {
		return x.CollisionGrid
	}
	return nil
}

func (x *MapData) GetGridWidth() uint32 {
	if x != nil {
		return x.GridWidth
	}
	return 0
}

func (x *MapData) GetGridHeight() uint32 {
	if x != nil {
		return x.GridHeight
	}
	return 0
}

func (x *MapData) GetSpawnPoints() []*SpawnPoint {
	if x != nil {
		return x.SpawnPoints
	}
	return nil
}

type SpawnPoint struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpawnPoint) Reset() {
	*x = SpawnPoint{}
	mi := &file_game_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpawnPoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpawnPoint) ProtoMessage() {}

func (x *SpawnPoint) ProtoReflect() protoreflect.Message {
	mi := &file_game_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpawnPoint.ProtoReflect.Descriptor instead.
func (*SpawnPoint) Descriptor() ([]byte, []int) {
	return file_game_proto_rawDescGZIP(), []int{1}
}

func (x *SpawnPoint) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpawnPoint) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

var File_game_proto protoreflect.FileDescriptor

const file_game_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"game.proto\x12\apackets\"\x96\x02\n" +
	"\aMapData\x12\x14\n" +
	"\x05width\x18\x01 \x01(\rR\x05width\x12\x16\n" +
	"\x06height\x18\x02 \x01(\rR\x06height\x12\x1d\n" +
	"\n" +
	"tile_width\x18\x03 \x01(\rR\ttileWidth\x12\x1f\n" +
	"\vtile_height\x18\x04 \x01(\rR\n" +
	"tileHeight\x12%\n" +
	"\x0ecollision_grid\x18\x05 \x03(\rR\rcollisionGrid\x12\x1d\n" +
	"\n" +
	"grid_width\x18\x06 \x01(\rR\tgridWidth\x12\x1f\n" +
	"\vgrid_height\x18\a \x01(\rR\n" +
	"gridHeight\x126\n" +
	"\fspawn_points\x18\b \x03(\v2\x13.packets.SpawnPointR\vspawnPoints\"(\n" +
	"\n" +
	"SpawnPoint\x12\f\n" +
	"\x01x\x18\x01 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x02R\x01yB\rZ\vpkg/packetsb\x06proto3"

var (
	file_game_proto_rawDescOnce sync.Once
	file_game_proto_rawDescData []byte
)

func file_game_proto_rawDescGZIP() []byte {
	file_game_proto_rawDescOnce.Do(func() {
		file_game_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)))
	})
	return file_game_proto_rawDescData
}

var file_game_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_game_proto_goTypes = []any{
	(*MapData)(nil),    // 0: packets.MapData
	(*SpawnPoint)(nil), // 1: packets.SpawnPoint
}
var file_game_proto_depIdxs = []int32{
	1, // 0: packets.MapData.spawn_points:type_name -> packets.SpawnPoint
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_game_proto_init() }
func file_game_proto_init() {
	if File_game_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_game_proto_rawDesc), len(file_game_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_game_proto_goTypes,
		DependencyIndexes: file_game_proto_depIdxs,
		MessageInfos:      file_game_proto_msgTypes,
	}.Build()
	File_game_proto = out.File
	file_game_proto_goTypes = nil
	file_game_proto_depIdxs = nil
}
