// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Id
	//	*Packet_Chat
	//	*Packet_DenyResponse
	//	*Packet_OkResponse
	//	*Packet_Disconnect
	//	*Packet_LoginRequest
	//	*Packet_LoginResponse
	//	*Packet_RegisterRequest
	//	*Packet_MapData
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDisconnect() *DisconnectMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetLoginResponse() *LoginResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginResponse); ok {
			return x.LoginResponse
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetMapData() *MapData {
	if x != nil {
		if x, ok := x.Msg.(*Packet_MapData); ok {
			return x.MapData
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Id struct {
	// ===== Common =====
	Id *IdMessage `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponse `protobuf:"bytes,7,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OkResponse `protobuf:"bytes,6,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_Disconnect struct {
	Disconnect *DisconnectMessage `protobuf:"bytes,19,opt,name=disconnect,proto3,oneof"`
}

type Packet_LoginRequest struct {
	// ===== Auth =====
	LoginRequest *LoginRequest `protobuf:"bytes,4,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,5,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,20,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_MapData struct {
	// ===== Game =====
	MapData *MapData `protobuf:"bytes,50,opt,name=map_data,json=mapData,proto3,oneof"`
}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_Disconnect) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_LoginResponse) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_MapData) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\x1a\fcommon.proto\x1a\n" +
	"auth.proto\x1a\n" +
	"game.proto\"\xa7\x04\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12$\n" +
	"\x02id\x18\x02 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12*\n" +
	"\x04chat\x18\x03 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12<\n" +
	"\rdeny_response\x18\a \x01(\v2\x15.packets.DenyResponseH\x00R\fdenyResponse\x126\n" +
	"\vok_response\x18\x06 \x01(\v2\x13.packets.OkResponseH\x00R\n" +
	"okResponse\x12<\n" +
	"\n" +
	"disconnect\x18\x13 \x01(\v2\x1a.packets.DisconnectMessageH\x00R\n" +
	"disconnect\x12<\n" +
	"\rlogin_request\x18\x04 \x01(\v2\x15.packets.LoginRequestH\x00R\floginRequest\x12?\n" +
	"\x0elogin_response\x18\x05 \x01(\v2\x16.packets.LoginResponseH\x00R\rloginResponse\x12E\n" +
	"\x10register_request\x18\x14 \x01(\v2\x18.packets.RegisterRequestH\x00R\x0fregisterRequest\x12-\n" +
	"\bmap_data\x182 \x01(\v2\x10.packets.MapDataH\x00R\amapDataB\x05\n" +
	"\x03msgB\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packets_proto_goTypes = []any{
	(*Packet)(nil),            // 0: packets.Packet
	(*IdMessage)(nil),         // 1: packets.IdMessage
	(*ChatMessage)(nil),       // 2: packets.ChatMessage
	(*DenyResponse)(nil),      // 3: packets.DenyResponse
	(*OkResponse)(nil),        // 4: packets.OkResponse
	(*DisconnectMessage)(nil), // 5: packets.DisconnectMessage
	(*LoginRequest)(nil),      // 6: packets.LoginRequest
	(*LoginResponse)(nil),     // 7: packets.LoginResponse
	(*RegisterRequest)(nil),   // 8: packets.RegisterRequest
	(*MapData)(nil),           // 9: packets.MapData
}
var file_packets_proto_depIdxs = []int32{
	1, // 0: packets.Packet.id:type_name -> packets.IdMessage
	2, // 1: packets.Packet.chat:type_name -> packets.ChatMessage
	3, // 2: packets.Packet.deny_response:type_name -> packets.DenyResponse
	4, // 3: packets.Packet.ok_response:type_name -> packets.OkResponse
	5, // 4: packets.Packet.disconnect:type_name -> packets.DisconnectMessage
	6, // 5: packets.Packet.login_request:type_name -> packets.LoginRequest
	7, // 6: packets.Packet.login_response:type_name -> packets.LoginResponse
	8, // 7: packets.Packet.register_request:type_name -> packets.RegisterRequest
	9, // 8: packets.Packet.map_data:type_name -> packets.MapData
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_common_proto_init()
	file_auth_proto_init()
	file_game_proto_init()
	file_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Id)(nil),
		(*Packet_Chat)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_Disconnect)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_LoginResponse)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_MapData)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
