// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: packets.proto

package packets

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Packet struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	SenderId uint64                 `protobuf:"varint,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Types that are valid to be assigned to Msg:
	//
	//	*Packet_Id
	//	*Packet_Chat
	//	*Packet_DenyResponse
	//	*Packet_OkResponse
	//	*Packet_Disconnect
	//	*Packet_LoginRequest
	//	*Packet_LoginResponse
	//	*Packet_RegisterRequest
	//	*Packet_RoomInfo
	//	*Packet_CreateRoomRequest
	//	*Packet_CreateRoomResponse
	//	*Packet_JoinRoomRequest
	//	*Packet_JoinRoomResponse
	//	*Packet_LeaveRoomRequest
	//	*Packet_StartGameRequest
	//	*Packet_RoomJoined
	//	*Packet_User
	Msg           isPacket_Msg `protobuf_oneof:"msg"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Packet) Reset() {
	*x = Packet{}
	mi := &file_packets_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Packet) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Packet) ProtoMessage() {}

func (x *Packet) ProtoReflect() protoreflect.Message {
	mi := &file_packets_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Packet.ProtoReflect.Descriptor instead.
func (*Packet) Descriptor() ([]byte, []int) {
	return file_packets_proto_rawDescGZIP(), []int{0}
}

func (x *Packet) GetSenderId() uint64 {
	if x != nil {
		return x.SenderId
	}
	return 0
}

func (x *Packet) GetMsg() isPacket_Msg {
	if x != nil {
		return x.Msg
	}
	return nil
}

func (x *Packet) GetId() *IdMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Id); ok {
			return x.Id
		}
	}
	return nil
}

func (x *Packet) GetChat() *ChatMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Chat); ok {
			return x.Chat
		}
	}
	return nil
}

func (x *Packet) GetDenyResponse() *DenyResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_DenyResponse); ok {
			return x.DenyResponse
		}
	}
	return nil
}

func (x *Packet) GetOkResponse() *OkResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_OkResponse); ok {
			return x.OkResponse
		}
	}
	return nil
}

func (x *Packet) GetDisconnect() *DisconnectMessage {
	if x != nil {
		if x, ok := x.Msg.(*Packet_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

func (x *Packet) GetLoginRequest() *LoginRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginRequest); ok {
			return x.LoginRequest
		}
	}
	return nil
}

func (x *Packet) GetLoginResponse() *LoginResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LoginResponse); ok {
			return x.LoginResponse
		}
	}
	return nil
}

func (x *Packet) GetRegisterRequest() *RegisterRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RegisterRequest); ok {
			return x.RegisterRequest
		}
	}
	return nil
}

func (x *Packet) GetRoomInfo() *RoomInfo {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomInfo); ok {
			return x.RoomInfo
		}
	}
	return nil
}

func (x *Packet) GetCreateRoomRequest() *CreateRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateRoomRequest); ok {
			return x.CreateRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetCreateRoomResponse() *CreateRoomResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_CreateRoomResponse); ok {
			return x.CreateRoomResponse
		}
	}
	return nil
}

func (x *Packet) GetJoinRoomRequest() *JoinRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoomRequest); ok {
			return x.JoinRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetJoinRoomResponse() *JoinRoomResponse {
	if x != nil {
		if x, ok := x.Msg.(*Packet_JoinRoomResponse); ok {
			return x.JoinRoomResponse
		}
	}
	return nil
}

func (x *Packet) GetLeaveRoomRequest() *LeaveRoomRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_LeaveRoomRequest); ok {
			return x.LeaveRoomRequest
		}
	}
	return nil
}

func (x *Packet) GetStartGameRequest() *StartGameRequest {
	if x != nil {
		if x, ok := x.Msg.(*Packet_StartGameRequest); ok {
			return x.StartGameRequest
		}
	}
	return nil
}

func (x *Packet) GetRoomJoined() *RoomJoined {
	if x != nil {
		if x, ok := x.Msg.(*Packet_RoomJoined); ok {
			return x.RoomJoined
		}
	}
	return nil
}

func (x *Packet) GetUser() *User {
	if x != nil {
		if x, ok := x.Msg.(*Packet_User); ok {
			return x.User
		}
	}
	return nil
}

type isPacket_Msg interface {
	isPacket_Msg()
}

type Packet_Id struct {
	// common
	Id *IdMessage `protobuf:"bytes,2,opt,name=id,proto3,oneof"`
}

type Packet_Chat struct {
	Chat *ChatMessage `protobuf:"bytes,3,opt,name=chat,proto3,oneof"`
}

type Packet_DenyResponse struct {
	DenyResponse *DenyResponse `protobuf:"bytes,7,opt,name=deny_response,json=denyResponse,proto3,oneof"`
}

type Packet_OkResponse struct {
	OkResponse *OkResponse `protobuf:"bytes,6,opt,name=ok_response,json=okResponse,proto3,oneof"`
}

type Packet_Disconnect struct {
	Disconnect *DisconnectMessage `protobuf:"bytes,19,opt,name=disconnect,proto3,oneof"`
}

type Packet_LoginRequest struct {
	// auth
	LoginRequest *LoginRequest `protobuf:"bytes,4,opt,name=login_request,json=loginRequest,proto3,oneof"`
}

type Packet_LoginResponse struct {
	LoginResponse *LoginResponse `protobuf:"bytes,5,opt,name=login_response,json=loginResponse,proto3,oneof"`
}

type Packet_RegisterRequest struct {
	RegisterRequest *RegisterRequest `protobuf:"bytes,20,opt,name=register_request,json=registerRequest,proto3,oneof"`
}

type Packet_RoomInfo struct {
	// hall
	RoomInfo *RoomInfo `protobuf:"bytes,9,opt,name=room_info,json=roomInfo,proto3,oneof"`
}

type Packet_CreateRoomRequest struct {
	CreateRoomRequest *CreateRoomRequest `protobuf:"bytes,12,opt,name=create_room_request,json=createRoomRequest,proto3,oneof"`
}

type Packet_CreateRoomResponse struct {
	CreateRoomResponse *CreateRoomResponse `protobuf:"bytes,13,opt,name=create_room_response,json=createRoomResponse,proto3,oneof"`
}

type Packet_JoinRoomRequest struct {
	JoinRoomRequest *JoinRoomRequest `protobuf:"bytes,14,opt,name=join_room_request,json=joinRoomRequest,proto3,oneof"`
}

type Packet_JoinRoomResponse struct {
	JoinRoomResponse *JoinRoomResponse `protobuf:"bytes,15,opt,name=join_room_response,json=joinRoomResponse,proto3,oneof"`
}

type Packet_LeaveRoomRequest struct {
	LeaveRoomRequest *LeaveRoomRequest `protobuf:"bytes,21,opt,name=leave_room_request,json=leaveRoomRequest,proto3,oneof"`
}

type Packet_StartGameRequest struct {
	StartGameRequest *StartGameRequest `protobuf:"bytes,22,opt,name=start_game_request,json=startGameRequest,proto3,oneof"`
}

type Packet_RoomJoined struct {
	RoomJoined *RoomJoined `protobuf:"bytes,17,opt,name=room_joined,json=roomJoined,proto3,oneof"`
}

type Packet_User struct {
	User *User `protobuf:"bytes,18,opt,name=user,proto3,oneof"`
}

func (*Packet_Id) isPacket_Msg() {}

func (*Packet_Chat) isPacket_Msg() {}

func (*Packet_DenyResponse) isPacket_Msg() {}

func (*Packet_OkResponse) isPacket_Msg() {}

func (*Packet_Disconnect) isPacket_Msg() {}

func (*Packet_LoginRequest) isPacket_Msg() {}

func (*Packet_LoginResponse) isPacket_Msg() {}

func (*Packet_RegisterRequest) isPacket_Msg() {}

func (*Packet_RoomInfo) isPacket_Msg() {}

func (*Packet_CreateRoomRequest) isPacket_Msg() {}

func (*Packet_CreateRoomResponse) isPacket_Msg() {}

func (*Packet_JoinRoomRequest) isPacket_Msg() {}

func (*Packet_JoinRoomResponse) isPacket_Msg() {}

func (*Packet_LeaveRoomRequest) isPacket_Msg() {}

func (*Packet_StartGameRequest) isPacket_Msg() {}

func (*Packet_RoomJoined) isPacket_Msg() {}

func (*Packet_User) isPacket_Msg() {}

var File_packets_proto protoreflect.FileDescriptor

const file_packets_proto_rawDesc = "" +
	"\n" +
	"\rpackets.proto\x12\apackets\x1a\fcommon.proto\x1a\n" +
	"auth.proto\x1a\n" +
	"hall.proto\"\xcf\b\n" +
	"\x06Packet\x12\x1b\n" +
	"\tsender_id\x18\x01 \x01(\x04R\bsenderId\x12$\n" +
	"\x02id\x18\x02 \x01(\v2\x12.packets.IdMessageH\x00R\x02id\x12*\n" +
	"\x04chat\x18\x03 \x01(\v2\x14.packets.ChatMessageH\x00R\x04chat\x12<\n" +
	"\rdeny_response\x18\a \x01(\v2\x15.packets.DenyResponseH\x00R\fdenyResponse\x126\n" +
	"\vok_response\x18\x06 \x01(\v2\x13.packets.OkResponseH\x00R\n" +
	"okResponse\x12<\n" +
	"\n" +
	"disconnect\x18\x13 \x01(\v2\x1a.packets.DisconnectMessageH\x00R\n" +
	"disconnect\x12<\n" +
	"\rlogin_request\x18\x04 \x01(\v2\x15.packets.LoginRequestH\x00R\floginRequest\x12?\n" +
	"\x0elogin_response\x18\x05 \x01(\v2\x16.packets.LoginResponseH\x00R\rloginResponse\x12E\n" +
	"\x10register_request\x18\x14 \x01(\v2\x18.packets.RegisterRequestH\x00R\x0fregisterRequest\x120\n" +
	"\troom_info\x18\t \x01(\v2\x11.packets.RoomInfoH\x00R\broomInfo\x12L\n" +
	"\x13create_room_request\x18\f \x01(\v2\x1a.packets.CreateRoomRequestH\x00R\x11createRoomRequest\x12O\n" +
	"\x14create_room_response\x18\r \x01(\v2\x1b.packets.CreateRoomResponseH\x00R\x12createRoomResponse\x12F\n" +
	"\x11join_room_request\x18\x0e \x01(\v2\x18.packets.JoinRoomRequestH\x00R\x0fjoinRoomRequest\x12I\n" +
	"\x12join_room_response\x18\x0f \x01(\v2\x19.packets.JoinRoomResponseH\x00R\x10joinRoomResponse\x12I\n" +
	"\x12leave_room_request\x18\x15 \x01(\v2\x19.packets.LeaveRoomRequestH\x00R\x10leaveRoomRequest\x12I\n" +
	"\x12start_game_request\x18\x16 \x01(\v2\x19.packets.StartGameRequestH\x00R\x10startGameRequest\x126\n" +
	"\vroom_joined\x18\x11 \x01(\v2\x13.packets.RoomJoinedH\x00R\n" +
	"roomJoined\x12#\n" +
	"\x04user\x18\x12 \x01(\v2\r.packets.UserH\x00R\x04userB\x05\n" +
	"\x03msgB\rZ\vpkg/packetsb\x06proto3"

var (
	file_packets_proto_rawDescOnce sync.Once
	file_packets_proto_rawDescData []byte
)

func file_packets_proto_rawDescGZIP() []byte {
	file_packets_proto_rawDescOnce.Do(func() {
		file_packets_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)))
	})
	return file_packets_proto_rawDescData
}

var file_packets_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_packets_proto_goTypes = []any{
	(*Packet)(nil),             // 0: packets.Packet
	(*IdMessage)(nil),          // 1: packets.IdMessage
	(*ChatMessage)(nil),        // 2: packets.ChatMessage
	(*DenyResponse)(nil),       // 3: packets.DenyResponse
	(*OkResponse)(nil),         // 4: packets.OkResponse
	(*DisconnectMessage)(nil),  // 5: packets.DisconnectMessage
	(*LoginRequest)(nil),       // 6: packets.LoginRequest
	(*LoginResponse)(nil),      // 7: packets.LoginResponse
	(*RegisterRequest)(nil),    // 8: packets.RegisterRequest
	(*RoomInfo)(nil),           // 9: packets.RoomInfo
	(*CreateRoomRequest)(nil),  // 10: packets.CreateRoomRequest
	(*CreateRoomResponse)(nil), // 11: packets.CreateRoomResponse
	(*JoinRoomRequest)(nil),    // 12: packets.JoinRoomRequest
	(*JoinRoomResponse)(nil),   // 13: packets.JoinRoomResponse
	(*LeaveRoomRequest)(nil),   // 14: packets.LeaveRoomRequest
	(*StartGameRequest)(nil),   // 15: packets.StartGameRequest
	(*RoomJoined)(nil),         // 16: packets.RoomJoined
	(*User)(nil),               // 17: packets.User
}
var file_packets_proto_depIdxs = []int32{
	1,  // 0: packets.Packet.id:type_name -> packets.IdMessage
	2,  // 1: packets.Packet.chat:type_name -> packets.ChatMessage
	3,  // 2: packets.Packet.deny_response:type_name -> packets.DenyResponse
	4,  // 3: packets.Packet.ok_response:type_name -> packets.OkResponse
	5,  // 4: packets.Packet.disconnect:type_name -> packets.DisconnectMessage
	6,  // 5: packets.Packet.login_request:type_name -> packets.LoginRequest
	7,  // 6: packets.Packet.login_response:type_name -> packets.LoginResponse
	8,  // 7: packets.Packet.register_request:type_name -> packets.RegisterRequest
	9,  // 8: packets.Packet.room_info:type_name -> packets.RoomInfo
	10, // 9: packets.Packet.create_room_request:type_name -> packets.CreateRoomRequest
	11, // 10: packets.Packet.create_room_response:type_name -> packets.CreateRoomResponse
	12, // 11: packets.Packet.join_room_request:type_name -> packets.JoinRoomRequest
	13, // 12: packets.Packet.join_room_response:type_name -> packets.JoinRoomResponse
	14, // 13: packets.Packet.leave_room_request:type_name -> packets.LeaveRoomRequest
	15, // 14: packets.Packet.start_game_request:type_name -> packets.StartGameRequest
	16, // 15: packets.Packet.room_joined:type_name -> packets.RoomJoined
	17, // 16: packets.Packet.user:type_name -> packets.User
	17, // [17:17] is the sub-list for method output_type
	17, // [17:17] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_packets_proto_init() }
func file_packets_proto_init() {
	if File_packets_proto != nil {
		return
	}
	file_common_proto_init()
	file_auth_proto_init()
	file_hall_proto_init()
	file_packets_proto_msgTypes[0].OneofWrappers = []any{
		(*Packet_Id)(nil),
		(*Packet_Chat)(nil),
		(*Packet_DenyResponse)(nil),
		(*Packet_OkResponse)(nil),
		(*Packet_Disconnect)(nil),
		(*Packet_LoginRequest)(nil),
		(*Packet_LoginResponse)(nil),
		(*Packet_RegisterRequest)(nil),
		(*Packet_RoomInfo)(nil),
		(*Packet_CreateRoomRequest)(nil),
		(*Packet_CreateRoomResponse)(nil),
		(*Packet_JoinRoomRequest)(nil),
		(*Packet_JoinRoomResponse)(nil),
		(*Packet_LeaveRoomRequest)(nil),
		(*Packet_StartGameRequest)(nil),
		(*Packet_RoomJoined)(nil),
		(*Packet_User)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_packets_proto_rawDesc), len(file_packets_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_packets_proto_goTypes,
		DependencyIndexes: file_packets_proto_depIdxs,
		MessageInfos:      file_packets_proto_msgTypes,
	}.Build()
	File_packets_proto = out.File
	file_packets_proto_goTypes = nil
	file_packets_proto_depIdxs = nil
}
