# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x07packets\"$\n\x04User\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\"\x1e\n\tIdMessage\x12\x11\n\tclient_id\x18\x01 \x01(\x04\"\x1a\n\x0b\x43hatMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1e\n\x0c\x44\x65nyResponse\x12\x0e\n\x06reason\x18\x01 \x01(\t\"\x0c\n\nOkResponseB\rZ\x0bpkg/packetsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013pkg/packets'
  _globals['_USER']._serialized_start=25
  _globals['_USER']._serialized_end=61
  _globals['_IDMESSAGE']._serialized_start=63
  _globals['_IDMESSAGE']._serialized_end=93
  _globals['_CHATMESSAGE']._serialized_start=95
  _globals['_CHATMESSAGE']._serialized_end=121
  _globals['_DENYRESPONSE']._serialized_start=123
  _globals['_DENYRESPONSE']._serialized_end=153
  _globals['_OKRESPONSE']._serialized_start=155
  _globals['_OKRESPONSE']._serialized_end=167
# @@protoc_insertion_point(module_scope)
