# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: game.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'game.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\ngame.proto\x12\x07packets\x1a\x0c\x63ommon.proto\"d\n\nPlayerList\x12\x1e\n\x07players\x18\x01 \x03(\x0b\x32\r.packets.User\x12!\n\nroom_owner\x18\x02 \x01(\x0b\x32\r.packets.User\x12\x13\n\x0bmax_players\x18\x03 \x01(\r\"-\n\x0cPlayerJoined\x12\x1d\n\x06player\x18\x01 \x01(\x0b\x32\r.packets.User\"1\n\nPlayerLeft\x12\x11\n\tplayer_id\x18\x01 \x01(\x04\x12\x10\n\x08username\x18\x02 \x01(\t\"\x12\n\x10StartGameRequest\"4\n\x11StartGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x1f\n\x0cGameStarting\x12\x0f\n\x07room_id\x18\x01 \x01(\x04\x42\rZ\x0bpkg/packetsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'game_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013pkg/packets'
  _globals['_PLAYERLIST']._serialized_start=37
  _globals['_PLAYERLIST']._serialized_end=137
  _globals['_PLAYERJOINED']._serialized_start=139
  _globals['_PLAYERJOINED']._serialized_end=184
  _globals['_PLAYERLEFT']._serialized_start=186
  _globals['_PLAYERLEFT']._serialized_end=235
  _globals['_STARTGAMEREQUEST']._serialized_start=237
  _globals['_STARTGAMEREQUEST']._serialized_end=255
  _globals['_STARTGAMERESPONSE']._serialized_start=257
  _globals['_STARTGAMERESPONSE']._serialized_end=309
  _globals['_GAMESTARTING']._serialized_start=311
  _globals['_GAMESTARTING']._serialized_end=342
# @@protoc_insertion_point(module_scope)
