# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'packets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpackets.proto\x12\x07packets\"\x1a\n\x0b\x43hatMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x17\n\tIdMessage\x12\n\n\x02id\x18\x01 \x01(\x04\"9\n\x13LoginRequestMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"<\n\x16RegisterRequestMessage\x12\x10\n\x08username\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x13\n\x11OkResponseMessage\"%\n\x13\x44\x65nyResponseMessage\x12\x0e\n\x06reason\x18\x02 \x01(\t\"?\n\rPlayerMessage\x12\n\n\x02id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\t\n\x01x\x18\x03 \x01(\x01\x12\t\n\x01y\x18\x04 \x01(\x01\"\xf2\x02\n\x06Packet\x12\x11\n\tsender_id\x18\x01 \x01(\x04\x12$\n\x04\x63hat\x18\x02 \x01(\x0b\x32\x14.packets.ChatMessageH\x00\x12 \n\x02id\x18\x03 \x01(\x0b\x32\x12.packets.IdMessageH\x00\x12\x35\n\rlogin_request\x18\x04 \x01(\x0b\x32\x1c.packets.LoginRequestMessageH\x00\x12;\n\x10register_request\x18\x05 \x01(\x0b\x32\x1f.packets.RegisterRequestMessageH\x00\x12\x31\n\x0bok_response\x18\x06 \x01(\x0b\x32\x1a.packets.OkResponseMessageH\x00\x12\x35\n\rdeny_response\x18\x07 \x01(\x0b\x32\x1c.packets.DenyResponseMessageH\x00\x12(\n\x06player\x18\x08 \x01(\x0b\x32\x16.packets.PlayerMessageH\x00\x42\x05\n\x03msgB\rZ\x0bpkg/packetsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013pkg/packets'
  _globals['_CHATMESSAGE']._serialized_start=26
  _globals['_CHATMESSAGE']._serialized_end=52
  _globals['_IDMESSAGE']._serialized_start=54
  _globals['_IDMESSAGE']._serialized_end=77
  _globals['_LOGINREQUESTMESSAGE']._serialized_start=79
  _globals['_LOGINREQUESTMESSAGE']._serialized_end=136
  _globals['_REGISTERREQUESTMESSAGE']._serialized_start=138
  _globals['_REGISTERREQUESTMESSAGE']._serialized_end=198
  _globals['_OKRESPONSEMESSAGE']._serialized_start=200
  _globals['_OKRESPONSEMESSAGE']._serialized_end=219
  _globals['_DENYRESPONSEMESSAGE']._serialized_start=221
  _globals['_DENYRESPONSEMESSAGE']._serialized_end=258
  _globals['_PLAYERMESSAGE']._serialized_start=260
  _globals['_PLAYERMESSAGE']._serialized_end=323
  _globals['_PACKET']._serialized_start=326
  _globals['_PACKET']._serialized_end=696
# @@protoc_insertion_point(module_scope)
