# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: packets.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'packets.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpackets.proto\x12\x07packets\"\x1a\n\x0b\x43hatMessage\x12\x0b\n\x03msg\x18\x01 \x01(\t\"H\n\x06Packet\x12\x11\n\tsender_id\x18\x01 \x01(\x04\x12$\n\x04\x63hat\x18\x02 \x01(\x0b\x32\x14.packets.ChatMessageH\x00\x42\x05\n\x03msgB\rZ\x0bpkg/packetsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'packets_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013pkg/packets'
  _globals['_CHATMESSAGE']._serialized_start=26
  _globals['_CHATMESSAGE']._serialized_end=52
  _globals['_PACKET']._serialized_start=54
  _globals['_PACKET']._serialized_end=126
# @@protoc_insertion_point(module_scope)
