# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: room.proto
# Protobuf Python Version: 7.35.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    0,
    '',
    'room.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nroom.proto\x12\x07packets\x1a\x0c\x63ommon.proto\"\xc5\x01\n\x08RoomInfo\x12\x0f\n\x07room_id\x18\x01 \x01(\x04\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x14\n\x0cplayer_count\x18\x03 \x01(\r\x12\x13\n\x0bmax_players\x18\x04 \x01(\r\x12!\n\nroom_owner\x18\x05 \x01(\x0b\x32\r.packets.User\x12(\n\x06status\x18\x06 \x01(\x0e\x32\x18.packets.RoomInfo.Status\"\"\n\x06Status\x12\x0b\n\x07WAITING\x10\x00\x12\x0b\n\x07PLAYING\x10\x01\"\x12\n\x10ListRoomsRequest\"5\n\x11ListRoomsResponse\x12 \n\x05rooms\x18\x01 \x03(\x0b\x32\x11.packets.RoomInfo\"6\n\x11\x43reateRoomRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x13\n\x0bmax_players\x18\x02 \x01(\r\"V\n\x12\x43reateRoomResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1f\n\x04room\x18\x03 \x01(\x0b\x32\x11.packets.RoomInfo\"\"\n\x0fJoinRoomRequest\x12\x0f\n\x07room_id\x18\x01 \x01(\x04\"r\n\x10JoinRoomResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\x12\x1f\n\x04room\x18\x03 \x01(\x0b\x32\x11.packets.RoomInfo\x12\x1c\n\x05users\x18\x04 \x03(\x0b\x32\r.packets.User\"\x12\n\x10LeaveRoomRequest\"4\n\x11LeaveRoomResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x12\n\x10StartGameRequest\"4\n\x11StartGameResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"\x8a\x02\n\nRoomUpdate\x12\x1f\n\x04room\x18\x01 \x01(\x0b\x32\x11.packets.RoomInfo\x12\x1c\n\x05users\x18\x02 \x03(\x0b\x32\r.packets.User\x12,\n\x04type\x18\x03 \x01(\x0e\x32\x1e.packets.RoomUpdate.UpdateType\x12\"\n\x0btarget_user\x18\x04 \x01(\x0b\x32\r.packets.User\"k\n\nUpdateType\x12\x11\n\rPLAYER_JOINED\x10\x00\x12\x0f\n\x0bPLAYER_LEFT\x10\x01\x12\x11\n\rOWNER_CHANGED\x10\x02\x12\x12\n\x0eSTATUS_CHANGED\x10\x03\x12\x12\n\x0eROOM_DESTROYED\x10\x04\"\x1f\n\x0cGameStarting\x12\x0f\n\x07room_id\x18\x01 \x01(\x04\x42\rZ\x0bpkg/packetsb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'room_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\013pkg/packets'
  _globals['_ROOMINFO']._serialized_start=38
  _globals['_ROOMINFO']._serialized_end=235
  _globals['_ROOMINFO_STATUS']._serialized_start=201
  _globals['_ROOMINFO_STATUS']._serialized_end=235
  _globals['_LISTROOMSREQUEST']._serialized_start=237
  _globals['_LISTROOMSREQUEST']._serialized_end=255
  _globals['_LISTROOMSRESPONSE']._serialized_start=257
  _globals['_LISTROOMSRESPONSE']._serialized_end=310
  _globals['_CREATEROOMREQUEST']._serialized_start=312
  _globals['_CREATEROOMREQUEST']._serialized_end=366
  _globals['_CREATEROOMRESPONSE']._serialized_start=368
  _globals['_CREATEROOMRESPONSE']._serialized_end=454
  _globals['_JOINROOMREQUEST']._serialized_start=456
  _globals['_JOINROOMREQUEST']._serialized_end=490
  _globals['_JOINROOMRESPONSE']._serialized_start=492
  _globals['_JOINROOMRESPONSE']._serialized_end=606
  _globals['_LEAVEROOMREQUEST']._serialized_start=608
  _globals['_LEAVEROOMREQUEST']._serialized_end=626
  _globals['_LEAVEROOMRESPONSE']._serialized_start=628
  _globals['_LEAVEROOMRESPONSE']._serialized_end=680
  _globals['_STARTGAMEREQUEST']._serialized_start=682
  _globals['_STARTGAMEREQUEST']._serialized_end=700
  _globals['_STARTGAMERESPONSE']._serialized_start=702
  _globals['_STARTGAMERESPONSE']._serialized_end=754
  _globals['_ROOMUPDATE']._serialized_start=757
  _globals['_ROOMUPDATE']._serialized_end=1023
  _globals['_ROOMUPDATE_UPDATETYPE']._serialized_start=916
  _globals['_ROOMUPDATE_UPDATETYPE']._serialized_end=1023
  _globals['_GAMESTARTING']._serialized_start=1025
  _globals['_GAMESTARTING']._serialized_end=1056
# @@protoc_insertion_point(module_scope)
